modLoader="javafml"
loaderVersion="[31,)"
license="MIT"
issueTrackerURL="https://github.com/Jummit/stack-down/issues"
[[mods]]
modId="stackdown"
version="${file.jarVersion}"
displayName="StackDown"
authors="Jummit"
description='''
Set or modify the max stack size of items with a config.
'''
